version: 0.2

phases:
  install:
    commands:
      - wget -qO- https://deb.nodesource.com/setup_8.x | sudo -E bash -
      - sudo apt-get install -y nodejs
  build:
    commands:
      - ./build.sh
