#!/bin/bash

unpack() {
  echo "Unzipping world"
  unzip -q /data/world.zip
  rm -f /data/world.zip
  if [ ! -d /data/world ]; then
    echo "World directory not found"
    for i in /data/*/level.dat; do
      if [ -f "$i" ]; then
        d=`dirname "$i"`
        echo "Renaming world directory from $d"
        mv -f "$d" /data/world
      fi
    done
  fi
  if [ "$TYPE" = "SPIGOT" ]; then
    # Reorganise if a Spigot server
    echo "Moving End and Nether maps to Spigot location"
    [ -d "/data/world/DIM1" ] && mv -f "/data/world/DIM1" "/data/world_the_end"
    [ -d "/data/world/DIM-1" ] && mv -f "/data/world/DIM-1" "/data/world_nether"
  fi
}

# If supplied with a URL for a world, download it and unpack
if [[ "$WORLD" ]]; then
case "X$WORLD" in
  X[Hh][Tt][Tt][Pp]*)
    echo "Downloading $WORLD via HTTP"
    wget -q -O - "$WORLD" > /data/world.zip
    unpack
    ;;
  X[Ss]3*)
    echo "Downloading $WORLD via S3 copy"
    aws s3 cp $WORLD /data/world.zip
    unpack
    ;;
  *)
    echo "Invalid URL given for world: Must be HTTP or HTTPS and a ZIP file"
    ;;
esac
fi

exec /start-finalSetup02Modpack $@
